[build]
  # 这是一个纯静态网站，无需构建
  publish = "public"
  command = ""

[functions]
  # 定义函数目录
  directory = "netlify/functions"
  
[build.environment]
  # 明确设置为不使用Python
  PYTHON_VERSION = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 